inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "Gemfile"

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: expanded

RSpec/NotToNot:
  EnforcedStyle: to_not
