@startuml yonde
hide circle

skinparam linetype ortho

entity "users" as users {
  id
  --
  first_name
  last_name
  nickname
  introduction
  phone_number
  email
  email_verified_at
  password
  remember_token
  icon_url
  is_host
  created_at
  updated_at
  deleted_at
}

entity "notifications" as notifications {
  id
  --
  user_id<<FK>>
  body
  created_at
  updated_at
}

entity "sns_credentials" as sns_credentials {
  id
  --
  user_id<<FK>>
  provider
  uid
  created_at
  updated_at
}

entity "sns_urls" as sns_urls {
  id
  --
  user_id<<FK>>
  url
  created_at
  updated_at
}

entity "events" as events {
  id
  --
  user_id<<FK>>
  title
  subtitle
  discription
  thumbnail_url
  price
  required_time
  place
  is_published
  capacity
  created_at
  updated_at
  deleted_at
}

entity "event_images" as event_images {
  id
  --
  event_id<<FK>>
  image_url
  created_at
  updated_at
}

entity "event_reviews" as event_reviews {
  id
  --
  user_id<<FK>>
  event_id<<FK>>
  five_ster_rating
  review
  created_at
  updated_at
}


entity "hosted_dates" as hosted_dates {
  id
  --
  event_id<<FK>>
  date
  created_at
  updated_at
}

entity "reservations" as reservations {
  reservation_number
  --
  user_id<<FK>>
  event_id<<FK>>
  memo
  guest_number
  is_canceled
  created_at
  updated_at
}

entity "event_favorites" as event_favorites {
  id
  --
  user_id<<FK>>
  event_id<<FK>>
  created_at
  updated_at
}

entity "event_contacts" as event_contacts {
  id
  --
  user_id<<FK>>
  event_id<<FK>>
  body
  created_at
  updated_at
}

' entity "password_resets" as password_resets {
'   --
'   email
'   token
'   created_at
' }

users ||--o{ events
users ||--o{ event_favorites
users ||--o{ reservations
users ||--o{ sns_urls
users ||--o{ event_reviews
users ||--o{ sns_credentials
users ||--o{ notifications
users ||--o{ event_contacts
events ||--o{ event_favorites
events ||--|{ event_images
events ||--|{ hosted_dates
events ||--o{ event_contacts
events ||--o{ reservations
events ||--o{ event_reviews

@enduml
